LOCAL_PATH := $(call my-dir)

#
# Prebuilt APKs
#

#MKexplorer_2.4.0
include $(CLEAR_VARS)
LOCAL_MODULE := MKexplorer
LOCAL_MODULE_OWNER := lineage
LOCAL_SRC_FILES := app/$(LOCAL_MODULE).apk
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_SUFFIX := .apk
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
include $(BUILD_PREBUILT)